### ISSUE TITLE
Can you take a look at this bug for me？

### ISSUE THREAD

**Issue by Suelence-hu** [FenHua/DetDak#1]
![image](https://user-images.githubusercontent.com/39931365/99246351-21803380-2840-11eb-82a9-76319a43ca31.png)

**Comment by FenHua** [comment]
This bug is due to problems with the PyTorch version, and you can try other versions or change the configuration accordingly. We have modified the scripts in MMCV so that the back propagation could be normal.

mmdetetction is not recommended if it is not necessary.

mmcv/ops/nms.py  line:113   we charge the type of  "inds"  to numpy and  "keep" to numpy
